env: prod
db:
  url: postgres://user:password@address:port/adtelligent
  updateCacheDelay: 60s
  bigRequestTimeout: 5s
server:
  auctionPort: 80
  stitchingPort: 81
  timeout: 4s
  idleTimeout: 60s
stitching:
  auctionUrl: http://address:port/auction
  requestTimeout: 1s
